import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'LUCHSARY',
  description: 'Generated by create next app',

}
 
export default function RootLayout({ children }) {

  return (
    <html lang="en" >
      <head>
<link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png" />
 
      </head>
      <body className="w-screen "> 
       {children}
        </body>
    </html>

  )
}
