import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'LUCHSARY',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {
  return (
    <html lang="en" uft>
   
      <body className="w-screen   ">
      <nav className='bg-blue-600  p-4   flex justify-end gap-3   text-yellow-50 uppercase ' >
        <div  className="w-fit mx-auto left-3   absolute" >
             <svg xmlns="http://www.w3.org/2000/svg" fill="none"viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
         <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
         </svg>
        </div>
  
        <Link href="/dashbord" className=''>dashbord</Link>
        <Link href="/" className=''>Home</Link>

       </nav>
        {children}
        
        </body>
    </html>
  )
}
