import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })
import Sidebar from './Components/Sidebar'
export const metadata = {
  title: 'LUCHSARY',
  description: 'Generated by create next app',

}
 
export default function RootLayout({ children }) {

  return (
    <html lang="en" >
      <head>
      {/* <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/> */}
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
{/* <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
<link rel="manifest" href="/site.webmanifest" /> */}
      </head>
      <body className="w-screen   ">
      <nav className='bg-blue-600  p-4   flex justify-end gap-3   text-yellow-50 uppercase ' >
        <Sidebar/>
        <Link href="/dashbord" className=''>dashbord</Link>
        <Link href="/" className=''>Home</Link>
       </nav>    
       {children}
        </body>
    </html>

  )
}
